# Generated by Django 5.1.3 on 2024-12-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_sluug_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sluug',
            new_name='slug',
        ),
    ]
